/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IOzcarEscrow } from "./IOzcarEscrow";
export type { OzcarLoanDisbursement } from "./OzcarLoanDisbursement";
