/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ozcarLoanDisbursementSol from "./OzcarLoanDisbursement.sol";
export type { ozcarLoanDisbursementSol };
import type * as vehicleNftSol from "./VehicleNFT.sol";
export type { vehicleNftSol };
export type { Escrow } from "./Escrow";
export type { OzcarAppraisalNFT } from "./OzcarAppraisalNFT";
export type { OzcarEscrow } from "./OzcarEscrow";
export type { OzcarGovernance } from "./OzcarGovernance";
export type { OzcarNFT } from "./OzcarNFT";
export type { OzcarReputation } from "./OzcarReputation";
export type { OzcarRewardCalculator } from "./OzcarRewardCalculator";
export type { OzcarToken } from "./OzcarToken";
export type { OzcarTradeInSettlement } from "./OzcarTradeInSettlement";
export type { OzcarVehicleHistory } from "./OzcarVehicleHistory";
