/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace OzcarGovernance {
  export type VoteStruct = {
    juror: AddressLike;
    tier: BigNumberish;
    decision: boolean;
    votingPower: BigNumberish;
    timestamp: BigNumberish;
  };

  export type VoteStructOutput = [
    juror: string,
    tier: bigint,
    decision: boolean,
    votingPower: bigint,
    timestamp: bigint
  ] & {
    juror: string;
    tier: bigint;
    decision: boolean;
    votingPower: bigint;
    timestamp: bigint;
  };
}

export interface OzcarGovernanceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ANOMALY_THRESHOLD"
      | "CASE_DURATION"
      | "CITIZEN_MIN_STAKE"
      | "CITIZEN_VOTING_POWER"
      | "EXPERT_MIN_STAKE"
      | "EXPERT_VOTING_POWER"
      | "GRAND_JURY_MIN_STAKE"
      | "GRAND_JURY_VOTING_POWER"
      | "REWARD_POOL_PER_CASE"
      | "TARGET_CITIZEN_RATIO"
      | "TARGET_EXPERT_RATIO"
      | "TARGET_GRAND_JURY_RATIO"
      | "activeCases"
      | "activeJurors"
      | "caseVotes"
      | "cases"
      | "emergencyWithdraw"
      | "finalizeCase"
      | "getCaseVotes"
      | "getJurorStats"
      | "getPendingCases"
      | "getWeightedVotingPower"
      | "hasVoted"
      | "jurors"
      | "owner"
      | "ozcToken"
      | "registerAsJuror"
      | "renounceOwnership"
      | "reputation"
      | "submitCase"
      | "transferOwnership"
      | "upgradeTier"
      | "vote"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccuracyUpdated"
      | "AnomalyDetected"
      | "CaseFinalized"
      | "CaseSubmitted"
      | "JurorRegistered"
      | "JurorUpgraded"
      | "OwnershipTransferred"
      | "RewardDistributed"
      | "Voted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ANOMALY_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CASE_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CITIZEN_MIN_STAKE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CITIZEN_VOTING_POWER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EXPERT_MIN_STAKE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EXPERT_VOTING_POWER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GRAND_JURY_MIN_STAKE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GRAND_JURY_VOTING_POWER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REWARD_POOL_PER_CASE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TARGET_CITIZEN_RATIO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TARGET_EXPERT_RATIO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TARGET_GRAND_JURY_RATIO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeCases",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "activeJurors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "caseVotes",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "cases", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeCase",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCaseVotes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getJurorStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingCases",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWeightedVotingPower",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "jurors", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "ozcToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAsJuror",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitCase",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BytesLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "ANOMALY_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CASE_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CITIZEN_MIN_STAKE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CITIZEN_VOTING_POWER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EXPERT_MIN_STAKE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EXPERT_VOTING_POWER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GRAND_JURY_MIN_STAKE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GRAND_JURY_VOTING_POWER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REWARD_POOL_PER_CASE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TARGET_CITIZEN_RATIO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TARGET_EXPERT_RATIO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TARGET_GRAND_JURY_RATIO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeCases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeJurors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "caseVotes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cases", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeCase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCaseVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getJurorStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingCases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWeightedVotingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jurors", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ozcToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAsJuror",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reputation", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "submitCase", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
}

export namespace AccuracyUpdatedEvent {
  export type InputTuple = [juror: AddressLike, newAccuracy: BigNumberish];
  export type OutputTuple = [juror: string, newAccuracy: bigint];
  export interface OutputObject {
    juror: string;
    newAccuracy: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AnomalyDetectedEvent {
  export type InputTuple = [caseId: BytesLike, score: BigNumberish];
  export type OutputTuple = [caseId: string, score: bigint];
  export interface OutputObject {
    caseId: string;
    score: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CaseFinalizedEvent {
  export type InputTuple = [
    caseId: BytesLike,
    finalDecision: boolean,
    validVotes: BigNumberish,
    invalidVotes: BigNumberish
  ];
  export type OutputTuple = [
    caseId: string,
    finalDecision: boolean,
    validVotes: bigint,
    invalidVotes: bigint
  ];
  export interface OutputObject {
    caseId: string;
    finalDecision: boolean;
    validVotes: bigint;
    invalidVotes: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CaseSubmittedEvent {
  export type InputTuple = [
    caseId: BytesLike,
    caseType: BigNumberish,
    submitter: AddressLike
  ];
  export type OutputTuple = [
    caseId: string,
    caseType: bigint,
    submitter: string
  ];
  export interface OutputObject {
    caseId: string;
    caseType: bigint;
    submitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JurorRegisteredEvent {
  export type InputTuple = [juror: AddressLike, tier: BigNumberish];
  export type OutputTuple = [juror: string, tier: bigint];
  export interface OutputObject {
    juror: string;
    tier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JurorUpgradedEvent {
  export type InputTuple = [
    juror: AddressLike,
    oldTier: BigNumberish,
    newTier: BigNumberish
  ];
  export type OutputTuple = [juror: string, oldTier: bigint, newTier: bigint];
  export interface OutputObject {
    juror: string;
    oldTier: bigint;
    newTier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardDistributedEvent {
  export type InputTuple = [juror: AddressLike, amount: BigNumberish];
  export type OutputTuple = [juror: string, amount: bigint];
  export interface OutputObject {
    juror: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotedEvent {
  export type InputTuple = [
    caseId: BytesLike,
    juror: AddressLike,
    decision: boolean
  ];
  export type OutputTuple = [caseId: string, juror: string, decision: boolean];
  export interface OutputObject {
    caseId: string;
    juror: string;
    decision: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OzcarGovernance extends BaseContract {
  connect(runner?: ContractRunner | null): OzcarGovernance;
  waitForDeployment(): Promise<this>;

  interface: OzcarGovernanceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ANOMALY_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  CASE_DURATION: TypedContractMethod<[], [bigint], "view">;

  CITIZEN_MIN_STAKE: TypedContractMethod<[], [bigint], "view">;

  CITIZEN_VOTING_POWER: TypedContractMethod<[], [bigint], "view">;

  EXPERT_MIN_STAKE: TypedContractMethod<[], [bigint], "view">;

  EXPERT_VOTING_POWER: TypedContractMethod<[], [bigint], "view">;

  GRAND_JURY_MIN_STAKE: TypedContractMethod<[], [bigint], "view">;

  GRAND_JURY_VOTING_POWER: TypedContractMethod<[], [bigint], "view">;

  REWARD_POOL_PER_CASE: TypedContractMethod<[], [bigint], "view">;

  TARGET_CITIZEN_RATIO: TypedContractMethod<[], [bigint], "view">;

  TARGET_EXPERT_RATIO: TypedContractMethod<[], [bigint], "view">;

  TARGET_GRAND_JURY_RATIO: TypedContractMethod<[], [bigint], "view">;

  activeCases: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  activeJurors: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  caseVotes: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, bigint, boolean, bigint, bigint] & {
        juror: string;
        tier: bigint;
        decision: boolean;
        votingPower: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  cases: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        id: string;
        caseType: bigint;
        submitter: string;
        ipfsHash: string;
        createdAt: bigint;
        deadline: bigint;
        status: bigint;
        finalized: boolean;
        anomalyScore: bigint;
      }
    ],
    "view"
  >;

  emergencyWithdraw: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  finalizeCase: TypedContractMethod<
    [_caseId: BytesLike, _anomalyScore: BigNumberish],
    [void],
    "nonpayable"
  >;

  getCaseVotes: TypedContractMethod<
    [_caseId: BytesLike],
    [OzcarGovernance.VoteStructOutput[]],
    "view"
  >;

  getJurorStats: TypedContractMethod<
    [_juror: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        tier: bigint;
        votingPower: bigint;
        accuracy: bigint;
        totalVotes: bigint;
        correctVotes: bigint;
        isTrial: boolean;
      }
    ],
    "view"
  >;

  getPendingCases: TypedContractMethod<[], [string[]], "view">;

  getWeightedVotingPower: TypedContractMethod<
    [_juror: AddressLike],
    [bigint],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  jurors: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint
      ] & {
        wallet: string;
        tier: bigint;
        votingPower: bigint;
        accuracy: bigint;
        totalVotes: bigint;
        correctVotes: bigint;
        ownedVehicles: bigint;
        stakingAmount: bigint;
        isActive: boolean;
        isTrial: boolean;
        joinedAt: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  ozcToken: TypedContractMethod<[], [string], "view">;

  registerAsJuror: TypedContractMethod<
    [_ownedVehicles: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputation: TypedContractMethod<[], [string], "view">;

  submitCase: TypedContractMethod<
    [_caseType: BigNumberish, _ipfsHash: string],
    [string],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeTier: TypedContractMethod<
    [_newTier: BigNumberish],
    [void],
    "nonpayable"
  >;

  vote: TypedContractMethod<
    [_caseId: BytesLike, _decision: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ANOMALY_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CASE_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CITIZEN_MIN_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CITIZEN_VOTING_POWER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EXPERT_MIN_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EXPERT_VOTING_POWER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GRAND_JURY_MIN_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GRAND_JURY_VOTING_POWER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REWARD_POOL_PER_CASE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TARGET_CITIZEN_RATIO"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TARGET_EXPERT_RATIO"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TARGET_GRAND_JURY_RATIO"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activeCases"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "activeJurors"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "caseVotes"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, bigint, boolean, bigint, bigint] & {
        juror: string;
        tier: bigint;
        decision: boolean;
        votingPower: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cases"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        id: string;
        caseType: bigint;
        submitter: string;
        ipfsHash: string;
        createdAt: bigint;
        deadline: bigint;
        status: bigint;
        finalized: boolean;
        anomalyScore: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeCase"
  ): TypedContractMethod<
    [_caseId: BytesLike, _anomalyScore: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCaseVotes"
  ): TypedContractMethod<
    [_caseId: BytesLike],
    [OzcarGovernance.VoteStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJurorStats"
  ): TypedContractMethod<
    [_juror: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        tier: bigint;
        votingPower: bigint;
        accuracy: bigint;
        totalVotes: bigint;
        correctVotes: bigint;
        isTrial: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingCases"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getWeightedVotingPower"
  ): TypedContractMethod<[_juror: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "jurors"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint
      ] & {
        wallet: string;
        tier: bigint;
        votingPower: bigint;
        accuracy: bigint;
        totalVotes: bigint;
        correctVotes: bigint;
        ownedVehicles: bigint;
        stakingAmount: bigint;
        isActive: boolean;
        isTrial: boolean;
        joinedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ozcToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAsJuror"
  ): TypedContractMethod<[_ownedVehicles: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitCase"
  ): TypedContractMethod<
    [_caseType: BigNumberish, _ipfsHash: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeTier"
  ): TypedContractMethod<[_newTier: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [_caseId: BytesLike, _decision: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AccuracyUpdated"
  ): TypedContractEvent<
    AccuracyUpdatedEvent.InputTuple,
    AccuracyUpdatedEvent.OutputTuple,
    AccuracyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AnomalyDetected"
  ): TypedContractEvent<
    AnomalyDetectedEvent.InputTuple,
    AnomalyDetectedEvent.OutputTuple,
    AnomalyDetectedEvent.OutputObject
  >;
  getEvent(
    key: "CaseFinalized"
  ): TypedContractEvent<
    CaseFinalizedEvent.InputTuple,
    CaseFinalizedEvent.OutputTuple,
    CaseFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "CaseSubmitted"
  ): TypedContractEvent<
    CaseSubmittedEvent.InputTuple,
    CaseSubmittedEvent.OutputTuple,
    CaseSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "JurorRegistered"
  ): TypedContractEvent<
    JurorRegisteredEvent.InputTuple,
    JurorRegisteredEvent.OutputTuple,
    JurorRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "JurorUpgraded"
  ): TypedContractEvent<
    JurorUpgradedEvent.InputTuple,
    JurorUpgradedEvent.OutputTuple,
    JurorUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardDistributed"
  ): TypedContractEvent<
    RewardDistributedEvent.InputTuple,
    RewardDistributedEvent.OutputTuple,
    RewardDistributedEvent.OutputObject
  >;
  getEvent(
    key: "Voted"
  ): TypedContractEvent<
    VotedEvent.InputTuple,
    VotedEvent.OutputTuple,
    VotedEvent.OutputObject
  >;

  filters: {
    "AccuracyUpdated(address,uint256)": TypedContractEvent<
      AccuracyUpdatedEvent.InputTuple,
      AccuracyUpdatedEvent.OutputTuple,
      AccuracyUpdatedEvent.OutputObject
    >;
    AccuracyUpdated: TypedContractEvent<
      AccuracyUpdatedEvent.InputTuple,
      AccuracyUpdatedEvent.OutputTuple,
      AccuracyUpdatedEvent.OutputObject
    >;

    "AnomalyDetected(bytes32,uint256)": TypedContractEvent<
      AnomalyDetectedEvent.InputTuple,
      AnomalyDetectedEvent.OutputTuple,
      AnomalyDetectedEvent.OutputObject
    >;
    AnomalyDetected: TypedContractEvent<
      AnomalyDetectedEvent.InputTuple,
      AnomalyDetectedEvent.OutputTuple,
      AnomalyDetectedEvent.OutputObject
    >;

    "CaseFinalized(bytes32,bool,uint256,uint256)": TypedContractEvent<
      CaseFinalizedEvent.InputTuple,
      CaseFinalizedEvent.OutputTuple,
      CaseFinalizedEvent.OutputObject
    >;
    CaseFinalized: TypedContractEvent<
      CaseFinalizedEvent.InputTuple,
      CaseFinalizedEvent.OutputTuple,
      CaseFinalizedEvent.OutputObject
    >;

    "CaseSubmitted(bytes32,uint8,address)": TypedContractEvent<
      CaseSubmittedEvent.InputTuple,
      CaseSubmittedEvent.OutputTuple,
      CaseSubmittedEvent.OutputObject
    >;
    CaseSubmitted: TypedContractEvent<
      CaseSubmittedEvent.InputTuple,
      CaseSubmittedEvent.OutputTuple,
      CaseSubmittedEvent.OutputObject
    >;

    "JurorRegistered(address,uint8)": TypedContractEvent<
      JurorRegisteredEvent.InputTuple,
      JurorRegisteredEvent.OutputTuple,
      JurorRegisteredEvent.OutputObject
    >;
    JurorRegistered: TypedContractEvent<
      JurorRegisteredEvent.InputTuple,
      JurorRegisteredEvent.OutputTuple,
      JurorRegisteredEvent.OutputObject
    >;

    "JurorUpgraded(address,uint8,uint8)": TypedContractEvent<
      JurorUpgradedEvent.InputTuple,
      JurorUpgradedEvent.OutputTuple,
      JurorUpgradedEvent.OutputObject
    >;
    JurorUpgraded: TypedContractEvent<
      JurorUpgradedEvent.InputTuple,
      JurorUpgradedEvent.OutputTuple,
      JurorUpgradedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardDistributed(address,uint256)": TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
    RewardDistributed: TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;

    "Voted(bytes32,address,bool)": TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
    Voted: TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
  };
}
