/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IOzcarEscrow__factory } from "./IOzcarEscrow__factory";
export { OzcarLoanDisbursement__factory } from "./OzcarLoanDisbursement__factory";
