/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOzcarEscrow,
  IOzcarEscrowInterface,
} from "../../../contracts/OzcarLoanDisbursement.sol/IOzcarEscrow";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_escrowId",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_escrowId",
        type: "uint256",
      },
    ],
    name: "escrows",
    outputs: [
      {
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "buyer",
        type: "address",
      },
      {
        internalType: "address",
        name: "seller",
        type: "address",
      },
      {
        internalType: "address",
        name: "nftContract",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "state",
        type: "uint8",
      },
      {
        internalType: "bool",
        name: "isFunded",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IOzcarEscrow__factory {
  static readonly abi = _abi;
  static createInterface(): IOzcarEscrowInterface {
    return new Interface(_abi) as IOzcarEscrowInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IOzcarEscrow {
    return new Contract(address, _abi, runner) as unknown as IOzcarEscrow;
  }
}
