/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IOzcarGovernance } from "./IOzcarGovernance";
export type { OzcarJurySlashing } from "./OzcarJurySlashing";
