/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IOzcarGovernance__factory } from "./IOzcarGovernance__factory";
export { OzcarJurySlashing__factory } from "./OzcarJurySlashing__factory";
