/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOzcarGovernance,
  IOzcarGovernanceInterface,
} from "../../../contracts/OzcarJurySlashing.sol/IOzcarGovernance";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "caseId",
        type: "bytes32",
      },
    ],
    name: "cases",
    outputs: [
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
      {
        internalType: "enum IOzcarGovernance.CaseType",
        name: "caseType",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "submitter",
        type: "address",
      },
      {
        internalType: "string",
        name: "ipfsHash",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "createdAt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
      {
        internalType: "enum IOzcarGovernance.CaseStatus",
        name: "status",
        type: "uint8",
      },
      {
        internalType: "bool",
        name: "finalized",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "anomalyScore",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IOzcarGovernance__factory {
  static readonly abi = _abi;
  static createInterface(): IOzcarGovernanceInterface {
    return new Interface(_abi) as IOzcarGovernanceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IOzcarGovernance {
    return new Contract(address, _abi, runner) as unknown as IOzcarGovernance;
  }
}
